#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

sh ~/.config/polybar/launch.sh
sh ~/.config/screenlayout/triple-monitor-config.sh

wmname LG3D

bspc config border_width        4
bspc config window_gap          4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#0C1115"
bspc config active_border_color "#0C1115"
bspc config focused_border_color "#58a4ad"

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
